name = "streams-api-worker"
type = "webpack"
routes = [
  "api.woke.net/streams.json*",
  "api.woke.net/stats.json",
]

[vars]
CURRENT_SHEET_NAME = "Current Streams (sorted)"
ALL_SHEET_NAME = "All Streams"
TTL = 10

